spring.application.name  = quizzcards

spring.data.mongodb.uri      = mongodb://localhost:27017/quizzcards

# <------pour une base mongo atlas------>
#spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster-name>.mongodb.net/quizzcards