spring.application.name  = quizzcards
server.port = 9000

spring.data.mongodb.uri = mongodb://quizzcards:KHmb%232494QuizzCards@database:27017/quizzcards?authSource=admin
#spring.data.mongodb.uri = mongodb+srv://khadim_ahmad_mbaye:KHmb2494QuizzCards@cluster0.6w6rsgf.mongodb.net/quizzcards?retryWrites=true&w=majority&appName=Cluster0

#spring.security.oauth2.client.registration.github.client-id     = Ov23li2mbmdEbA9UtYP1
#spring.security.oauth2.client.registration.github.client-secret = 48056c87476973c9ab7cb58a16f247b6079b02cd
#spring.security.oauth2.client.registration.github.redirect-uri  = http://localhost:9000/login/oauth2/code/github
#spring.security.oauth2.client.registration.github.scope         = read:user,repo

spring.security.oauth2.client.registration.google.client-id     = 1080251404369-duffkknlipnjuerigbib8t4293r43crt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = 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
spring.security.oauth2.client.registration.google.redirect-uri  = ${CALL_BACK_URL}
spring.security.oauth2.client.registration.google.scope         = openid,profile,email

# Groq API
spring.ai.openai.api-key=...
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7
