
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mongodb_quizzcards
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: quizzcards
      MONGO_INITDB_ROOT_PASSWORD: KHmb#2494QuizzCards
    volumes:
      - mongo-data:/data/db
    networks:
      - quizzcards

  frontend:
    container_name: front_quizzcards
    build:
      context: ./quizzcards
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "80:80"
      #- "443:443"
    networks:
      - quizzcards
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: back_quizzcards
    build:
      context: ./backSpringBoot
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "9000:9000"
    networks:
      - quizzcards
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - IP_HOST=quizzcards.info
      - CALL_BACK_URL=http://quizzcards.info:9000/login/oauth2/code/google
    env_file:
      - .env
    restart: unless-stopped

networks:
  quizzcards:
    driver: bridge

volumes:
  mongo-data: